### ISSUE TITLE
Wartość strzałów i tarcz dla tokenCreature

### ISSUE THREAD

**Issue by magdamagda** [piotrek1234/neuro#6]
Obecnie przychowywane są tylko kierunki strzałów, co z wartościami?
To samo dotyczy tarcz.

**Comment by piotrek1234** [comment]
Przy większej sile ataku kierunki się powtarzają, np. 1,1,1,2,2. W sumie można dać unikalne kierunki w parze z siłą, ale nie wiem czy tak nie jest prościej. Tarcza tylko jest albo jej nie ma w konkretnym kierunku.

**Comment by piotrek1234** [comment]
Może faktycznie map(int, int) jako (kierunek, siła) dla ataku i map(int, bool) dla tarczy będzie wygodniejsze w użyciu. Czekam na potwierdzenie

**Comment by magdamagda** [comment]
Potwierdzam
